version: '3.9'

services:
  application:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/local/app
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200
      - 9300:9300
