version: '3.9'

services:
  web:
    build: .
    command: [ "bin/rails", "s", "-b", "0.0.0.0" ]
    environment:
      RAILS_ENV: "development"
      RAILS_LOG_TO_STDOUT: "true"
      SECRET_KEY_BASE: "1YAmKbPvk3+QZKoZjJY9lA=="
    ports:
      - 3000:3000
    volumes:
      - .:/usr/local/app
  job:
    build: .
    command: [ "bundle", "exec", "sidekiq", "-q", "default" ]
    environment:
      RAILS_ENV: "development"
      RAILS_LOG_TO_STDOUT: "true"
      SECRET_KEY_BASE: "1YAmKbPvk3+QZKoZjJY9lA=="
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.3
    environment:
      ELASTICSEARCH_HOST: "http://elasticsearch:9200"
    ports:
      - 5601:5601
  redis:
    image: redis:6.2.4
